using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("ExternalAuthenticationTesting.PlugIn")]
[assembly: AssemblyDescription("Visit the Apprenda website at http://www.apprenda.com/")]
[assembly: AssemblyConfiguration("This assembly was generated by kcamp at 10/28/2016 11:23:47.")]
[assembly: AssemblyCompany("Apprenda, Inc.")]
[assembly: AssemblyProduct("Apprenda Platform")]
[assembly: AssemblyCopyright("Copyright © Apprenda Inc. 2016")]
[assembly: AssemblyTrademark("Various trademarks held by their respective owners.")]
[assembly: ComVisible(false)]
[assembly: Guid("7feebd5a-bb4f-4b70-bb38-954df60989f7")]
[assembly: AssemblyFileVersion("6.6.0.0")]
[assembly: AssemblyVersion("6.6.0.0")]
